version: '3'

services:
  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    volumes:
      - ./_docker_volumes/pg_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "iCommerce"

